max_width = 79
combine_control_expr = false
condense_wildcard_suffixes = true
edition = "2018"
force_multiline_blocks = true
format_code_in_doc_comments = true
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
merge_derives = true
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
use_field_init_shorthand = true
